language: java
addons:
    srcclr: true
jdk:
  - oraclejdk8
before_script:
  chmod 777 gradlew
script:
  ./gradlew clean build checkCoverage --debug
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key: "$GIT_HUB"
  file: "build/libs/npm-mvn-proxy.jar"
  skip_cleanup: true
  on:
    tags: true